// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using serpost.monitoreo.data;

namespace serpost.monitoreo.data.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20200626185636_migration001")]
    partial class migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("serpost.monitoreo.core.Entities.archivos", b =>
                {
                    b.Property<short>("id_camara")
                        .HasColumnType("smallint");

                    b.Property<int>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("timestamp");

                    b.Property<string>("nombre_archivo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_camara", "id_archivo");

                    b.ToTable("archivos");
                });

            modelBuilder.Entity("serpost.monitoreo.core.Entities.camara", b =>
                {
                    b.Property<short>("id_camara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("url_camara")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("id_camara");

                    b.ToTable("camara");

                    b.HasData(
                        new
                        {
                            id_camara = (short)1,
                            url_camara = "http://10.147.17.111:3333/"
                        },
                        new
                        {
                            id_camara = (short)2,
                            url_camara = "http://10.147.17.99:8080/"
                        },
                        new
                        {
                            id_camara = (short)3,
                            url_camara = "http://10.147.17.20:8080/"
                        });
                });

            modelBuilder.Entity("serpost.monitoreo.core.Entities.ti_usuario_x_camara", b =>
                {
                    b.Property<short>("id_camara")
                        .HasColumnType("smallint");

                    b.Property<string>("username")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("activo")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("id_camara", "username");

                    b.HasIndex("username");

                    b.ToTable("ti_usuario_x_camara");

                    b.HasData(
                        new
                        {
                            id_camara = (short)1,
                            username = "CNICOLINI",
                            activo = true
                        },
                        new
                        {
                            id_camara = (short)1,
                            username = "ACHAVARRI",
                            activo = true
                        },
                        new
                        {
                            id_camara = (short)2,
                            username = "CNICOLINI",
                            activo = true
                        },
                        new
                        {
                            id_camara = (short)3,
                            username = "CNICOLINI",
                            activo = true
                        });
                });

            modelBuilder.Entity("serpost.monitoreo.core.Entities.usuario", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ap_materno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ap_paterno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string[]>("nombres")
                        .IsRequired()
                        .HasColumnType("varchar(50)[]");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("username");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            username = "CNICOLINI",
                            ap_materno = "RIVERO",
                            ap_paterno = "NICOLINI",
                            nombres = new[] { "CÉSAR", "GIANFRANCO" },
                            password = "123456"
                        },
                        new
                        {
                            username = "ACHAVARRI",
                            ap_materno = "FREIRE",
                            ap_paterno = "CHAVARRI",
                            nombres = new[] { "ALVARO", "ALONSO" },
                            password = "123456"
                        });
                });

            modelBuilder.Entity("serpost.monitoreo.core.Entities.archivos", b =>
                {
                    b.HasOne("serpost.monitoreo.core.Entities.camara", "camara")
                        .WithMany()
                        .HasForeignKey("id_camara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("serpost.monitoreo.core.Entities.ti_usuario_x_camara", b =>
                {
                    b.HasOne("serpost.monitoreo.core.Entities.camara", "camara")
                        .WithMany()
                        .HasForeignKey("id_camara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serpost.monitoreo.core.Entities.usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
